%Departments
department("Early Childhood and Primary Education").
department("Educational Leadership and Management").
department("Secondary & Tertiary Education").
department("Special Needs Education").

department("Agricultural and Plantation Engineering").
department("Civil Engineering").
department("Electrical and Computer Engineering").
department("Mechanical Engineering").
department("Mathematics and Philosophy of Engineering").
department("Textile and Apparel Technology").

department("Basic Sciences").
department("Medical Laboratory Sciences").
department("Nursing").
department("Pharmacy").
department("Psychology and Counselling").

department("English Language Teaching (DELT)").
department("Language Studies").
department("Legal Studies").
department("Social Studies").

department("Botany").
department("Chemistry").
department("Computer Science").
department("Mathematics").
department("Physics").
department("Zoology").

department("Accounting and Finance").
department("Human Resource Management").
department("Marketing Management").
department("Organizational Studies").


%Department Link
department_link("Early Childhood and Primary Education", "The Department of Early Childhood and Primary Education, which was established in year 1999, conducts training programmes for preschool teachers.\n\n
In addition, the department coordinates the activities of the three model pre-schools situated in the three Regional Centres of the OUSL, the day care centre at Colombo (Nawala) Regional Centre and the Child Study Centre. The total number of permanent academic staff attached to the department is five. However, the Department gets the services from a large number of visiting academics to conduct day schools, mark assignments and assess practical courses of the teacher training programmes.\n\nMore Info visit this Link : https://ou.ac.lk/earlychildhood/").
department_link("Educational Leadership and Management", "The Department of Educational Leadership and Management (DELM) is the newly established Departments of the Faculty of Education, OUSL. In the university system of Sri Lanka, it will be the first department inaugurated for the field of Educational Leadership and management which is an immemorial landmark in the history of education in Sri Lanka.\n\n
The main objective of the new department is to strengthen the structure of educational management in Sri Lanka, through the development of leadership and management skills of those educational leaders such as principals, Directors of Education, and educationalists at various levels in the field of Education. Many such programs have been planned by the new department, as, for example, the Post Graduate Diploma in Educational Leadership and Management (PGDELM), B.Ed (Honours) Degree in Educational Leadership and Management and Diploma in School Management programs based on the Open and Distance Learning Method of Education, with a variety of learning techniques. Including an online learning environment.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-educational-leadership-and-management/").
department_link("Secondary & Tertiary Education", "The Department of Secondary & Tertiary Education is one of the pioneering Departments of the OUSL which was originally named as Department of Education. It currently serves around 3500 students enrolled in seven different study programmes, out of which five are Post Graduate level programmes. The Department also offers a stand-alone On-line course, a short course in Research Methodology and a short course in Multi-grade Teaching. In addition, the Department is responsible for coordinating two modules of the B.A. in English Language Teaching Programme conducted by the Department of Language Studies. Currently 23 academic members, and 03 non-academic staff serve the Department. Around 100 visiting academics and 400 Master Teachers from other Universities, National Colleges of Education, National Institute of Education and schools help the Department in the conduct of day school sessions, tutorials, teaching practice and marking of assignments.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-secondary-tertiary-education/").
department_link("Special Needs Education", "The Department of Special Needs Education was established in February 2004. The overall aim of the department is to help realize the objectives of the Child Resource Centre with regard to the assurance of rights of the children with special needs and those placed in special circumstances which Sri Lanka has pledged to implement.\n\n
The Department of Special Needs Education of the Faculty of Education of the Open University of Sri Lanka has been conducting the Degree in Bachelor of Education in Special Needs Education programme since 2013. The main purpose of this programme is to develop professional competencies needed to serve as an effective teacher to respond the special educational needs of all students. The Department offers this programme to empower those who intend to work in the field of special needs education with the knowledge, skills, attitudes, and confidence.\n\n
The OUSL is in conformity with the Sri Lanka Qualification Framework (SLQF). Accordingly, Bachelor of Education Honors in Special Needs Education Degree Programme [(B.Ed.Hons(Special Needs Education)] is restructured in line with SLQF.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-special-needs-education/").

department_link("Agricultural and Plantation Engineering", "The Department of Agricultural and Plantation Engineering offers courses to individuals who intend to choose Agriculture as their career in the future and enhance working capacity of those who are already working in the field, targeting high levels of productivity and sustainability.\n\n
The department offers a Bachelor of Industrial Studies Honours in Agriculture and Bachelor of Technology Honours in Engineering in the field of Agricultural Engineering.\n\n
Under the Bachelor of Industrial Studies Honours in Agriculture a wide array of courses are offered, including Crop Production, Plant and Soil Science, Plant protection, Biotechnology, Fisheries and aquaculture, Animal Husbandry, Food Processing, Agricultural Extension, Economics and Management, Agricultural Farm Machinery, Post-harvest technology, Water resources management and Irrigation.\n\n
Bachelor of Technology Honours in Engineering in the field of Agricultural Engineering started in 2020/2021 academic year  targeting to full fill a gap in between the Agriculture and the Engineering disciplines giving highest priority to the Engineering Mechanics, Crop Technology, Postharvest Engineering and Technology, Designing Agricultural Machine Elements, Design and Management of Irrigation and Drainage, Surveying, Workshop Practice, Economics and Marketing for Engineers, Soil Management Tillage and Traction, Crop Processing, Farm Power and Mechanization, Horticultural Landscaping Technology, Sustainable Agricultural Technology, Agricultural Hydrology, Precision Agriculture, Remote Sensing and GIS and Food Engineering.\n\n
Both these undergraduate programme is having a compulsory research course where the students are exposed to the problems in the field of Agriculture and find solutions to such problems by collarbrating with national agricultural research institute, private companies and universities. At the end of the project students are expected to submit a thesis and publish their findings in the journals and conference proceedings.\n\n
Further opportunities are provided to undertake research leading to the award of M.Phil and PhD degrees under the supervision of competent staff.\n\nMore Info visit this Link : https://ou.ac.lk/agri/").
department_link("Civil Engineering", "Department of Civil Engineering, the Open University of Sri Lanka, with a history of more than 35 years is the 3rd oldest of its kind in Sri Lanka. Currently around 1600 students are studying for their Bachelor of Technology Honours in Civil Engineering Degree. There is an annual intake of around 400 students to follow the Civil Engineering Degree in the Department, and is probably the largest Civil Engineering Department in the country. The Department is ably supported by qualified and well experienced staff consisting of Senior Professors, Professors, Senior Lecturers with PhD’s & postgraduate and professional qualifications with field experience. In addition to the conduct of Civil Engineering Degree programme, the Department contributes to teaching of all engineering undergraduates in the Faculty in the initial levels and also conducts Civil Engineering oriented courses for other engineering programmes from the second year onwards. The department has a strong relationship with the industry and utilizes their services in curriculum development and the teaching programme in order to produce Civil Engineering graduates of the highest calibre.\n\n
The department offers a Masters in Structural Engineering postgraduate programme to enhance the capability of practicing engineers as a part of their continuous professional development. The department also provides ample opportunities for postgraduate training in advanced research. The academic staff of the department are actively engaged in research and development activities and consultancy projects which are supported by local and foreign funding agencies. Our department offers a rich and diverse program consisting of both studies and research opportunities for undergraduate and postgraduate students to produce competent Civil Engineers who can actively contribute to the national development efforts and to undertake advanced research.\n\n
The Department has strong active links with industry and is very committed to continuing and developing these ties. The importance we place on the movement of our research to practice cannot be overstated. It is fundamental to whom we are, and what the Department is all about.\n\n
Civil Engineering is the major profession that is involved with the planning design and execution of development programmes aimed at enhancing the overall quality of life for the people at all levels of the society.\n\n
More specifically, Civil Engineers are responsible for the Investigation, Planning, Design and Construction of;\n\n
1.Bridges, Roads and Highways\n
2.Industrial Facilities\n
3.Buildings and commercial Structures\n
4.Railways, Harbours and Airports\n
5.Water Treatment/Supply systems and Water/Wastewater disposal systems\n
6.Coastal structures\n
7.Marine Structures\n
8.Hydro Power, Dams, Tunnels and Irrigation schemes\n
9.Environmental improvement facilities\n
10.Flood control and Ground\n
11.Improvement structures\n
12.Transportation & Conveyance Systems\n\n
It is also the responsibility of the Civil Engineer to ensure proper implementation and management of above projects to derive the highest possible benefit to the society.\n\nMore Info visit this Link : https://ou.ac.lk/civil/").
department_link("Electrical and Computer Engineering", "The Department of Electrical & Computer Engineering is the largest department within the Faculty, distinguished by its extensive student body. We offer a range of degree programmes, including:\n\n
1.Bachelor of Science Honours in Engineering specializing in Computer Engineering,\n
2.Bachelor of Science Honours in Engineering specializing in Electronics and Communication Engineering,\n
3.Bachelor of Science Honours in Engineering specializing in Electrical Engineering, and\n
4.Bachelor of Software Engineering (BSE) Honours.\n\n
A student can earn a Higher Diploma in any of the specializations mentioned above as an intermediate award. In addition to our Higher Diploma and undergraduate programs, we offer advanced research degrees, including MPhil and PhD, for students pursuing specialized research careers.\n\n
Our department is staffed by highly qualified and dedicated academic and non-academic professionals, ensuring a robust educational experience. Each year, we graduate well-prepared professionals who have consistently received accolades for their final year projects. Our students’ projects have been highly praised by leading professional bodies like the Institution of Engineers Sri Lanka (IESL) and have won several awards in competitions organized by IESL, the Sri Lanka Association for the Advancement of Science (SLAAS), and other esteemed institutions.\n\nMore Info visit this Link : https://ou.ac.lk/electrical/").
department_link("Mechanical Engineering", "The Department of Mechanical Engineering provides the students with opportunities to advance themselves in their career and become graduate engineers in the specialties of Mechanical Engineering and Mechatronics Engineering. The theoretical components of these specializations are amply supported with exposure to practical situations, in our reasonably well-equipped laboratories.\n\nMore Info visit this Link : https://ou.ac.lk/mechanical/").
department_link("Mathematics and Philosophy of Engineering", "The Department of Mathematics and Philosophy of Engineering provides several courses covering two schemes,\n\n

(i)     Mathematics and\n

(ii)    Philosophy of Engineering.\n\n

The mathematics related courses cover the knowledge of mathematics required by learners following the programmes offered by the Faculty of Engineering Technology and the life-long mathematical skills required to be successful professionals. The Philosophy of Engineering related courses cover the social, environmental, cultural, and philosophical aspects of science, technology, and engineering. They will be exposing the learners to broader non-technical perspectives and enhancing their capacity of working as professionals associated with the various social groups.\n\nMore Info visit this Link : https://ou.ac.lk/mathsandphilosophy/").
department_link("Textile and Apparel Technology", "Department of Textile and Apparel Technology of the Open University of Sri Lanka offers a wide variety of programmes and courses in the fields of textiles and apparel, from Certificate to the Postgraduate levels. As these courses are conducted using Distance and Open Learning methodologies, they are ideally suited for those who are employed and those who wish to pursue lifelong learning. The department is also involved in extension activities to the industry in the form of short courses and consultancies. It is prepared to undertake tailor made courses for the individual needs of particular organisations and industrial institutions. The department is endowed with differently qualified staff with wide experience in various fields of studies. The department is also involved in research activities in textile, apparel and distance education fields.\n\nMore Info visit this Link : https://ou.ac.lk/textile/").

department_link("Basic Sciences", "The Department of Basic Sciences was established on 9th June 2015 under the Faculty of Health Science of the Open University of Sri Lanka by extraordinary Gazette No. 1918/8 on 9th June 2015 after amending the Open University of Sri Lanka (Amendment) Ordinance, No. 1 of 1990 published in Gazette Extraordinary No. 591/18 of January 05, 1990 and amended by in Gazette Extraordinary No. 1839/41 of December 05, 2013 and further amended the paragraph 16 of the Open university ordinance as No. 02 of 2015 made under the University Grants Commission under Section 23(2) read with Section 18 of the Universities Act, No. 16 of 1978.\n\n
It is the one of six (06) Departments established under the Faculty of Health Sciences. The main task of the Department of Basic Sciences is to provide sound knowledge on the subject areas of Human Anatomy, Human Physiology, Pharmaceutical Chemistry, Statistics, Microbiology, Biochemistry and Pathophysiology for the degree programmes of Nursing, Medical Laboratory Sciences and Pharmacy.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-basic-sciences/").
department_link("Medical Laboratory Sciences", "Medical laboratory services play an important role in patient care as they contribute to clinical decisions with respect to disease prevention, diagnosis, treatment and the management of diseases. Over the years, the demand for qualified professionals in medical laboratory sciences has been increasing, nationally as well as internationally. As medical laboratory sciences is one of the most dynamic sciences, continuous advancement of the Medical Laboratory Scientists/Technologists is essential to make full use of the advances in technology for the improvement of human health.\n\n
The Department of Medical Laboratory Sciences at The Open University of Sri Lanka offers a Bachelor of Medical Laboratory Sciences Honours Degree programme for registered Medical Laboratory Technologists serving in the public and private sectors. The programme will also be open to school leavers in the near future. Those interested in a career in this field are invited to take the opportunity provided and enroll in the programme to graduate as a professional equipped with theoretical and practical competences relevant to the role of a Medical Scientist/Technologist.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-medical-laboratory-sciences/").
department_link("Nursing", "The Department of Nursing offers high-quality Degree programmes in Nursing in a vibrant and supportive learning environment to prepare nurses for a rewarding career in health care. In congruence with the principles of Open and Distance Learning (ODL) mode, the Department of Nursing is committed to foster student-faculty interaction and lifelong learning, facilitating nurses’ professional and personal development. To facilitate the learning environment further, academic activities of degree programmes have been decentralized to almost all Regional Centres of the Open University of Sri Lanka. Thus, nurses who are employed in any part of the island can create their own learning pace in accordance with their individual learning styles and needs.\n\n
Bachelor of Science Honours in Nursing  [BSc (Hons) in Nursing] degree program was launched in July 1994 in response to the request made by the Ministry of Health as of its first kind in the country.  This programme is designed to develop broad knowledge base needed by professional nurses to cater to the diverse and complex health care needs of the emerging society in a rapidly changing global community. With recent revisions, the BSc (Hons) in Nursing degree programme has been tailored to suit global nursing trends and individual career aspirations of nurses.\n\n
Similar to the BSc (Hons) in Nursing in Nursing degree, the Department of Nursing is ready to offer a Master of Science in Nursing  (MSc in Nursing) degree in year 2022 for registered nurses in the country as of its first kind in a state university in Sri Lanka. With the introduction of MSc in Nursing degree programme, the department is keen to fill the gap that has been created due to the unavailability of nursing postgraduate programmes in the Sri Lankan national university system.\n\n
We, as the Department of Nursing, are confident that you will have a wonderful learning experience at the OUSL, and the skills you gain from your studies will make a significant impact on the healthcare system.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-nursing/").
department_link("Pharmacy", "The Department of Pharmacy is one of the six Departments that make up the Faculty of Health Sciences at The Open University of Sri Lanka. Our Department conducts a professional Pharmacy undergraduate programme that leads to the Degree in Bachelor of Pharmacy (B.Pharm.) through open and distance learning methodologies.\n\n
Pharmacy is the profession responsible for the appropriate use of medications, devices and services in order to achieve optimal therapeutic outcomes. As such, pharmacists need to be well-equipped with knowledge, attitudes and skills required to deliver high quality, consistent and safe treatments to their clients. Thus, our B.Pharm. Degree Programme is designed to develop a professional Pharmacist with knowledge, favorable attitudes and skills in Pharmacy and Pharmaceutical Sciences to suit the needs of the healthcare sector and the relevant academic and research fields. Furthermore, we aim to develop motivated, self- directed learners who have the capacity to efficiently and effectively contribute to their profession and the work place, maintaining international standards.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-pharmacy/").
department_link("Psychology and Counselling", "Department of Psychology and Counselling strives to facilitate individuals to develop their theoretical knowledge of Psychology and practical skills in engaging with others. Psychology is the discipline that explores human behaviour within a scientific framework, through its various subfields of Counselling, Health, Educational, Organizational, Clinical and Developmental Psychology. We believe basic knowledge of human mind and behaviour is important and essential to many professionals engaged in Social work, Human resource management, Military, Business and Consumer areas. Anyone who is in contact with another individual at a supervisory, employee or customer relation level can also benefit from the knowledge of Psychology and the practical skills of the discipline.\n\n
Currently we offer a government recognized four-year BSc Honours Degree in Psychology with the highest level of quality and standards to those interested in learning about Psychology as a theoretical discipline. Also, this degree is for those for those interested in their personal development by learning practical skills of the profession, human behavior and thought processes within the Sri Lankan context.\n\n
The Department also administers the Counselling unit of the OUSL which plays a role in the health and wellbeing of the staff and students of the OUSL\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-psychology-and-counselling/").

department_link("English Language Teaching (DELT)", "The Department of English Language Teaching (DELT)was established in January 2020 in the Faculty of Humanities and Social Sciences. Establishing DELT was a major initiative to enhance the English Language skills of both undergraduate and postgraduate students of The Open University of Sri Lanka (OUSL) and to cater to the English language requirements of a wider population in the country.\n\n
We as a department focus on planning, developing and delivering innovative English Language programs and conducting research in the fields of teaching English for academic purposes and English as a second language. Currently, the department offers English for Academic Purposes (EAP) programs as support courses to all the undergraduates who register for degree programs in OUSL and one postgraduate program – Master of Arts in Teacher Education –(MATE International). Many new language programs are being planned and developed to be offered in the near future.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-department-of-english-language-teaching-delt/").
department_link("Language Studies", "The Department of Language Studies (LSD) offers a range of academic programmes that can cater to the needs of diverse group of students. It is committed to offering high quality programmes in the Distance Education mode utilizing innovative modes of teaching. In relation to English, the courses on offer are structured so that students can commence their studies with minimal levels of competence and proceed to a BA in English and English Language Teaching. The Department is also committed to serving the English language needs of all students registered for diverse undergraduate degrees at the OUSL. In recent times, we have also focused attention on enhancing learning opportunities for the two national languages of Sri Lanka: Sinhala and Tamil. The LSD thus offers a range of courses that are relevant to the Sri Lankan context with flexible and affordable avenues of learning where students can achieve professional, social and national goals.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-language-studies/").
department_link("Legal Studies", "Welcome to the Department of Legal Studies of the Open University of Sri Lanka. The  Department conducts a Bachelor of Laws degree programme and a Master of Laws in Criminal Justice Administration.\n\n    To be a centre of excellence for a new model of legal education in the 21st century that takes an interdisciplinary approach to law and public policy in developing solutions to national and global problems and challenges.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-legal-studies/").
department_link("Social Studies", "Welcome to the Department of Social Studies!\n
The Department of Social Studies is a multi-disciplinary academic division integrating the disciplines of Economics, Political Science, Sociology and Social Anthropology and Mass Communication. The Department has evolved with a distinct character and profile over the years, specialising in development studies while maintaining a strong foundation in the core disciplines.\n\n
The Department strongly believes that social science graduates with strong academic credentials, competencies and skills can contribute meaningfully to the country’s social and economic development and progress. Additionally, the department also believes social science graduates should learn to respect democratic values and cultural diversity while demonstrating a strong sense of civic responsibility and social responsiveness.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-social-studies/").

department_link("Botany", "Department of Botany offers Programmes ranging from Certificates, Advanced Certificates, Diplomas, Degrees, Postgraduate Diplomas and Master’s in Science through Open and Distance Learning for all those who wish to pursue higher education. In addition, we offer Foundation Courses as a qualifying course for those who have no formal qualifications and Stand Alone Courses for those who are interested in knowing more about certain areas or updating knowledge.\n\n
We make a valuable contribution to the B.Sc. Degree of the Faculty of Natural Sciences by effectively delivering both basic and more specialized course units resulting in products both knowledgeable and well-skilled in Botany both nationally and internationally.\n\n
Basic Botany courses offered at Levels 3 and 4 are designed to assist you to develop a good foundation based on which optional but industry-based course units are offered at Levels 5 & 6 in order to enhance the employment opportunities for our graduates.\n\n
Our Department is housed in the new Science & Technology building, Block 9 and Block 10 of the Colombo Regional Centre. Laboratory facilities for all courses are available at the central campus at Nawala in Block 9 &10. However, laboratory work for all Level 3 and some Level 4 & 5 courses is conducted at the Regional Centres in Kandy & Matara. A modern well equipped research laboratory is newly established in the S & T building.\n\n
To find out course details and other important information, please browse through the Botany web pages.\n\n
Hope you will find this experience rewarding and enjoyable. \n\nMore Info visit this Link : https://ou.ac.lk/botany/").
department_link("Chemistry", "Chemistry is one of the seven disciplines that are taught in the B.Sc Degree Programme of the Open University of Sri Lanka. Basic and foundation courses in Chemistry, which form the core for all higher level courses, are offered at tertiary levels a t 3 an d 4. These levels are equivalent to 1st and 2nd years of a conventional university. More applied and advanced courses in Chemistry are offered at levels 5 and 6. Since all level 5 and 6 courses in the Degree Programme are offered as optional courses, it is possible for a student who is interested in learning Chemistry to offer more courses in the subject area within the allowed number of courses at these levels.\n\n
The Department also offers Foundation level Chemistry courses at levels 1 and 2. Passing the required number of credits in disciplines of the foundation level will allow a student to enter the Bachelors Degree Programme.\n\n
The Department is housed in the new Science & Technology Building and Block 7 of the Colombo Regional Centre. Two undergraduate laboratories are in Block 15 & 18 of the Colombo Regional Centre while the Research Laboratory is in the Science and Technology Building. \n\nMore Info visit this Link : https://ou.ac.lk/chemistry/").
department_link("Computer Science", "We are happy to announce the establishment of the Department of Computer Science as the sixth department of the Faculty of Natural Sciences to contribute to the B.Sc degree programme by offering Computer Science as the seventh discipline. Our department is located on the third floor of the Science and Technology building of the Colombo Regional Center.\n\n
We have 20 years of experience in offering Computer Science discipline under the Department of Mathematics and Computer Science. This discipline is open for any student who satisfies the qualification to enter the B.Sc. Degree Programme, regardless of whether they have offered courses from the Bio Science or the Physical Science streams of the Advanced/Foundation level. The aim of the courses offered in the B.Sc degree programme is to develop competent personnel who are capable of assuming positions in the fields of Computer Science and Information Technology. In addition, we offer certificate programmes, tailor-made training programmes and short courses in computer application and networking, mainly to cater to user requirements.\n\n
To enhance the practical knowledge in Computer Science the department has a modern well-equipped computer science laboratory and a digital computer laboratory in the Colombo Regional Center. A computer science laboratory is also located at the Kandy Regional Center.\n\n
With the Department of Computer Science you will have the opportunity to enhance your knowledge, skills in computer science and information technology with passion for life-long learning. If you wish to know more about the Department of Computer Science and its services, please browse the Department web page. \n\nMore Info visit this Link : https://ou.ac.lk/computerscience/").
department_link("Mathematics", "Mathematics is the queen of Sciences. It is also said to be the language of Sciences. The necessity and the usefulness of Mathematics in Science is emerging and even better recognized in the modern society. Mathematics is all around us, in everything we do in our daily lives, including in the use of technology and digital devices, architecture, art, finance, engineering and even sports. Mathematics improves logical thinking and enhance analytical skills which are indeed needed to understand and effectively deal with real-life problems.\n\n
The Department of Mathematics welcomes students who wish to follow courses in the areas of Pure Mathematics, Applied Mathematics and Statistics mainly at undergraduate and post graduate level. In line with the mission of the University, the department guides students to become independent learners thus enabling them to pursue lifelong learning.The department offers well-structured courses designed in such a way to widen the horizons in the fields of Pure and Applied Mathematics.These courses are supported with course materials,well written in a learner friendly manner.\n\n
Department currently offers a Special Degree in Mathematics for students who have performed well in Level 3 and Level 4,and the department also plans to offer a Special Degree in Applied Mathematics and Statistics.\n\n
Depending on the availability of expertise, the department also welcomes students for M.Phil and Doctoral degrees.\n\n
In addition, the Department offers stand-alone courses in the areas of Applied Mathematics, Pure Mathematics and Statistics to cater to those who wish to enhance knowledge in the areas of their choice without registering for a regular Degree programme. Further, the Department provides statistical assistance to the Faculty. \n\nMore Info visit this Link : https://ou.ac.lk/mathematics/").
department_link("Physics", "Physics is one of the six (06) Departments in the Faculty of Natural Sciences at the Open University of Sri Lanka. Academic staff is housed at the second floor of the left wing of the Science and Technology building whereas undergraduate laboratories are located at Block 8 & 20 in the Colombo Regional Centre. Laboratories for undergraduate courses are also available at the Regional Centres in Kandy & Matara. A well equipped research laboratory with facilities for condense matter physics, electronics, geology, geophysics researches are located at the Science & Technology building.\n\n
Physics is taught in the B.Sc. degree programme in level 3, level 4 & level 5 (equivalent to first three years in conventional Universities) and also in the Foundation level courses in level 1 & 2, (equivalent to the G.C.E.Advance Level) passing of which enable students to enter the B.Sc. degree Programme. Core courses in physics in the B.Sc. Degree programme are taught in level 3 & 4 whereas level 5 courses are towards applied physics fields like astronomy, atmospheric physics, medical physics, biophysics, practical physics and nuclear physics. Basics such as fundamentals of geology, geophysics and environmental geology courses are also taught in level 5.\n\n
In addition to the academic programmes towards B.Sc. Degree, Department of physics offers Certificate courses in Applied Electronics and Applied Earth Sciences targeting professionals/employers and those who wish to gain more experiences in the particular field without completing a degree.\n\nMore Info visit this Link : https://ou.ac.lk/physics/").
department_link("Zoology", "The Department of Zoology is one of the oldest and well-established Departments of the OUSL, with more than 35 years of teaching and research experience. In keeping with the OUSL’s vision, we currently offer a range of academic programmes and courses through the open and distance learning methodology, including Degrees at undergraduate and postgraduate levels, Advanced Certificates, Diplomas, Certificates, stand-alone courses, and short courses in applied fields.\n\n
Our courses are diverse and provide an exciting opportunity to study about animals and their habitats, with laboratory and field activities incorporated to reinforce the theoretical concepts. The Department has qualified staff in different fields for the design and delivery of courses. The undergraduate and research laboratories and the museum support research activities and the practical components of the curricular offered.\n\n
Our staff-student Society – the ZooNet Society – organizes various academic and extracurricular activities throughout the year to support the all-round development of students and it is also a platform for students to showcase their academic achievements, talents, and skills.\n\n
Do explore the Department of Zoology website to learn more about our study programmes, research, and other initiatives. If you need further information, please contact the Head or relevant staff member using the contact details provided or we invite you to visit the Department of Zoology located on the ground floor of the Science & Technology building of the Central campus of the OUSL in Nawala. Zoology staff are also available for contact at selected Regional Centres of the OUSL.\n\nMore Info visit this Link : https://ou.ac.lk/zoology/").

department_link("Accounting and Finance", "The Department of Accounting and Finance is one of the leading academic departments in the Faculty of Management Studies. The department currently offers a wider array of courses utilizing the Open and Distance Learning (ODL) methodology, ranging from Certificate Level (level 02) to Post-graduate Level (Level 10). Staff members attached to the Department strive hard to maintain high standards of integrity and performance with a view to achieving academic and professional goals. The main focus of our department is to produce financially literate, competent, capable and dynamic personnel to serve the modern day requirements of the public and private sector organizations both locally and internationally.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-accounting-and-finance/").
department_link("Human Resource Management", "The bachelor of Management Studies degree program is carefully designed with the utmost intention for producing highly skilled management graduates specialized in Human Resource Management who will be ideal candidates to meet the highest industry standard in managerial competencies. Accomplished the that intention the department of human resource management officers innovative causes in the Human Resource Management discipline which promote understanding of the field both from a local and a global perspective.\n\n
The courses offered are designed in a way to enhance and strengthen the knowledge and skills of the learners through theoretical knowledge and industry experience. The courses in Human Resource Management intend to provide learners with opportunity to understand Human Resources Management has an integral part of the overall business of an organization. Further, it would create basis for the participants to acquire the competency to relate Human Resources Management with other functional areas of management. The Department offers a wide range of courses from advanced certificate level to post graduate levels. Certain courses offered as in inter-faculty courses for programmes offered by other faculties of the university.\n\n
We operate with a team of qualified and experienced staff committed to excellence. The Academic Staff is well connected with professionals in the corporate world facilitating the enhancement of management knowledge and skills. The partnership we maintain with the prominent professional human resource institute in the country contribute towards the value creation of the department at large.\n\n
Currently, our department offers/contribute to various study programs that are well recognized in the industry;\n\n
1.Master of Business Administration (MBA) Human Resource Management\n
2.Bachelor of Management Studies Degree Program (few courses)\n
3.Short Courses in Human Resource Management\n\n
At present the department of Human Resource Management is planning to broaden its scope by developing a specialized degree leading to a Bachelor of Management Studies Honors in Human Resource Management.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-human-resource-management/").
department_link("Marketing Management", "Our goal is to assist all those who are interested in pursuing a career in the field of Marketing to further strengthen their capacities and talents in order to become more creative and innovative. We are committed to achieve excellence in research and teaching and also keen on providing services that expand beyond mere classroom experience. Our expectation is to nurture a community of undergraduates, graduates, professionals, academics and researchers with sound knowledge in Marketing. The Department of Marketing will also explore every single opportunity to establish productive links with both local and international, public and private sector institutes with a view to strengthening and broad basing our research and teaching capacities. We will leave no stone unturned in providing the best possible services to our stake holders.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-marketing-management/").
department_link("Organizational Studies", "The Department of Organizational Studies of the Faculty of Management Studies aims to develop future managers for key positions in the corporate sector in both, local and global contexts who could command and grow in the managerial, information and communication technology sectors.\n\n
Our Department is structured according to multidisciplinary areas of management, namely: organizational behaviour and psychology, information systems, operations management, business strategy, quantitative techniques, entrepreneur development and study of new trends of management. The courses offered have been designed to enhance the knowledge and skills of the students through theoretical knowledge and industry experience and to provide exposure to highly recognized resource persons from the industry.\n\n
The Department offers a wide range of courses from advanced certificate level to postgraduate levels. Further, certain courses are offered as inter-faculty courses for programmes offered by other faculties of the university.\n\n
The Department of Organizational Studies operates with a team of qualified and experienced staff, committed to excellence. The academic staff is well connected with professionals in the corporate world facilitating the enhancement of management knowledge, skills. They are capable of inculcating essential personal values and attributes to improve the positive attitudes of learners to fit into the contemporary world of work.\n\n
The courses related to entrepreneurship are designed to benefit entrepreneurs and potential entrepreneurs to acquire new knowledge and skills to start new businesses or to manage their ongoing businesses. Further, the courses related to Information Technology, Operations Management, Quantitative Techniques and Public Administration offered through undergraduate and postgraduate degree programmes are developed in such a way to broaden the knowledge horizons of students for strategic use in business environments. Apart from that, the research component augments the skills of students by applying theoretical knowledge in real-life situations addressing managerial problems. As the emphasis of the research is to address a management-related issue or a problem, it is expected to empower students with the conceptual skills and analytical skills required for solving a problem.\n\n
At present, the Department is planning to broaden its context by developing specialization areas in the Legal Environment for Business, Entrepreneurship, Information and Communication systems for organizations and Operations and Logistics Management for the BMS (Honours) Degree Programme.\n\nMore Info visit this Link : https://ou.ac.lk/dept-of-organizational-studies/").

% Departments under each faculty
departmentof("Early Childhood and Primary Education", "Education").
departmentof("Educational Leadership and Management", "Education").
departmentof("Secondary & Tertiary Education", "Education").
departmentof("Special Needs Education", "Education").

departmentof("Agricultural and Plantation Engineering", "Engineering Technology").
departmentof("Civil Engineering", "Engineering Technology").
departmentof("Electrical and Computer Engineering", "Engineering Technology").
departmentof("Mechanical Engineering", "Engineering Technology").
departmentof("Mathematics and Philosophy of Engineering", "Engineering Technology").
departmentof("Textile and Apparel Technology", "Engineering Technology").

departmentof("Basic Sciences", "Health Science").
departmentof("Medical Laboratory Sciences", "Health Science").
departmentof("Nursing", "Health Science").
departmentof("Pharmacy", "Health Science").
departmentof("Psychology and Counselling", "Health Science").

departmentof("English Language Teaching (DELT)", "Humanities and Social Sciences").
departmentof("Language Studies", "Humanities and Social Sciences").
departmentof("Legal Studies", "Humanities and Social Sciences").
departmentof("Social Studies", "Humanities and Social Sciences").

departmentof("Botany", "Natural Sciences").
departmentof("Chemistry", "Natural Sciences").
departmentof("Computer Science", "Natural Sciences").
departmentof("Mathematics", "Natural Sciences").
departmentof("Physics", "Natural Sciences").
departmentof("Zoology", "Natural Sciences").

departmentof("Accounting and Finance", "Management Studies").
departmentof("Human Resource Management", "Management Studies").
departmentof("Marketing Management", "Management Studies").
departmentof("Organizational Studies", "Management Studies").
