% Faculties
faculty("Education").
faculty("Engineering Technology").
faculty("Health Science").
faculty("Humanities and Social Sciences").
faculty("Natural Sciences").
faculty("Management Studies").

%Faculty Link
faculty_link("Education", "The Faculty of Education offers a wide range of programmes from Certificate to Postgraduate levels in line with its vision to be a leader in the advancement of knowledge and professional practice in education as a fundamental endeavour through Open and Distance Learning in Sri Lanka and the Region. It is one of the largest providers of initial and continuous professional development programmes for teachers in the fields of preschool, primary and secondary and special needs education through the distance mode in Sri Lanka. The student enrolment in the programmes offered by the faculty is over 8000 in each academic year and the pass rate is above 80%. Research is an integral component of the activities within the Faculty and the staff members are actively involved in many research projects.\n\n
The Faculty of Education presently consists of the following four Departments of Study. Each Department is under a Head and all Departments are collectively responsible for the academic activities of the faculty.\n\n
1.Department of Secondary and Tertiary Education.\n
2.Department of Early Childhood and Primary Education.\n
3.Department of Special Needs Education.\n
4.Department of Educational Leadership and Management.\n\nMore Info visit this Link : https://ou.ac.lk/education/").

faculty_link("Engineering Technology", "Faculty of Engineering Technology offers a variety of study programmes leading to the awards of Certificates, Advanced Certificates, Higher Diplomas, Honors Bachelor Degrees, and Postgraduate Diplomas and Degrees encompassing a many engineering and industrial specializations as needed by the industry in line with the Sri Lanka Qualifications Frame Work. Major honors degrees awarded by the Faculty are the Bachelor of Science Honours in Engineering, Bachelor of Industrial Studies Honours, and Bachelor of Software Engineering Honours. In addition to the taught study programmes the Faculty through its well equipped academic departments facilitates research leading to the awards of MPhil and PhD degrees.\n\nMore Info visit this Link : https://ou.ac.lk/engineering/").

faculty_link("Health Science", "The Faculty of Health Sciences comprises the Academic Departments of Nursing, Medical Laboratory Sciences, Pharmacy, Basic Sciences, Psychology & Counseling, and Health Education & Research. We currently offer distance education programmes leading to Nursing, Medical Laboratory Sciences, Pharmacy and Psychology Degree qualifications. These programmes aim to develop competent personnel who are capable of assuming leadership positions, both in the academic and clinical sectors. With the Faculty of Health Sciences, you will have the opportunity to enhance your knowledge and skills, work towards a qualification, further develop your career and indulge in a passion for life-long learning!\n\nMore Info visit this Link : https://ou.ac.lk/health/").

faculty_link("Humanities and Social Sciences", "The Faculty of Humanities and Social Sciences is the largest Faculty of the Open University of Sri Lanka catering to over 10,000 students in the following programmes ranging from Foundation level to Master’s degree level under the four departments of the Faculty. The Faculty is made up of four Academic Departments including Language Studies, Legal Studies, Social Studies and English Language Teaching (DELT).\n\nMore Info visit this Link : https://ou.ac.lk/hss/").

faculty_link("Natural Sciences", "The Faculty of Natural Sciences has over 35 years of experience in delivering science degree programmes adopting the Open and Distance Learning (ODL) methodologies. The Faculty functions under the leadership of the Dean, who is the administrative and the academic head. It consists of six Departments: Botany, Chemistry, Computer Science, Mathematics, Physics and Zoology. In keeping with the mission and objectives of the Faculty, it currently offers 29 programmes of study ranging from Certificate to Postgraduate level, as well as stand-alone courses and short courses. The main undergraduate programmes offered by the Faculty are BSc degree programme and BSc (Hons) degree programmes with nearly 5,000 students.\n\n
The programmes of study offered by the Faculty of Natural Sciences are designed to develop competency in the area of specialisation, the soft skills and the technology needed for the 21st Century world of work. Further, learners are given several opportunities to enhance their career paths and continuously instil a passion for lifelong learning.\n\nMore Info visit this Link : https://ou.ac.lk/natural-sciences/").

faculty_link("Management Studies", "The Faculty of Management Studies (FMS) of OUSL was established with the purpose of imparting management knowledge for the development of management skills and appropriate management attitudes. In pursuance of this broad objective, services are provided to a wide spectrum of clients comprising young school leavers, managers, public administrators and small and medium scale entrepreneurs. The Faculty of Management Studies (FMS) comprises the Academic Departments of Organizational Studies (DOS), Accounting and Finance (DAF), Human Resource Management (DHR) and Marketing Management (DMM). The faculty is committed to the promotion of management education and research at undergraduate and postgraduate levels, we offer management education from certificate level to PhD level through Open and Distance Learning (ODL) methodologies.\n\nMore Info visit this Link : https://ou.ac.lk/management/").
